"""Add invite_code to users

Revision ID: f6e5732c8de9
Revises: 28d0ea449fd3
Create Date: 2025-05-24 01:41:45.491210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6e5732c8de9'
down_revision: Union[str, None] = '28d0ea449fd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('invite_code', sa.String(length=36), nullable=False))
    op.create_index(op.f('ix_users_invite_code'), 'users', ['invite_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_invite_code'), table_name='users')
    op.drop_column('users', 'invite_code')
    # ### end Alembic commands ###
